import {
  SEVERITY,
  SEVERITY_VALUES,
  describeSeverity,
} from "../domain/ticket-status";

export function renderTicketConsole(): string {
  return [
    "<!doctype html>",
    '<html lang="en">',
    "<head>",
    '  <meta charset="utf-8">',
    '  <meta name="viewport" content="width=device-width, initial-scale=1">',
    "  <title>Helpdesk · NestJS, Mongoose & enumwaii</title>",
    "  <style>",
    "    body { margin: 0; color: #18221e; background: #f6f4ee; font: 16px system-ui; }",
    "    .shell { max-width: 1000px; margin: auto; padding: 36px 20px; }",
    "    header, form { display: flex; gap: 12px; align-items: center; justify-content: space-between; flex-wrap: wrap; }",
    "    h1 { margin: 36px 0 12px; font: 500 clamp(44px, 7vw, 78px) Georgia; }",
    "    .lede, .meta { color: #57645c; line-height: 1.6; }",
    "    .panel { margin-top: 22px; padding: 22px; border: 1px solid #ddd8cb; border-radius: 18px; background: #fff; }",
    "    .tickets { display: grid; gap: 12px; }",
    "    .ticket { padding: 14px; border-left: 5px solid #497b70; border-radius: 8px; background: #f7faf7; }",
    "    button, input, select { padding: 9px; border: 1px solid #c7d0c9; border-radius: 8px; font: inherit; }",
    "    button { color: #fff; background: #275d4d; cursor: pointer; }",
    "  </style>",
    "</head>",
    "<body>",
    '  <main class="shell">',
    "    <header><strong>Helpdesk</strong><span>Mongo-backed ticket service</span></header>",
    "    <h1>Give every customer issue a clear next step.</h1>",
    '    <p class="lede">A support desk backend for tickets, severity-based SLAs, and versioned agent workflows.</p>',
    '    <section class="panel">',
    "      <h2>Open a ticket</h2>",
    '      <form id="create">',
    '        <input name="subject" required placeholder="Customer issue">',
    '        <select name="severity">' +
      SEVERITY_VALUES.map(
        (severity) =>
          `<option value="${severity}"${severity === SEVERITY.NORMAL ? " selected" : ""}>${describeSeverity(severity).label}</option>`,
      ).join("") +
      "</select>",
    '        <input name="memo" placeholder="Internal note">',
    "        <button>Create ticket</button>",
    "      </form>",
    "    </section>",
    '    <section class="panel">',
    "      <h2>Agent dashboard</h2>",
    '      <p class="meta">A stale write is reported as another agent having already moved the ticket.</p>',
    '      <div id="tickets" class="tickets">Loading tickets…</div>',
    "    </section>",
    "  </main>",
    "  <script>",
    '    const headers = { "content-type": "application/json" };',
    '    const ticketList = document.querySelector("#tickets");',
    "    async function api(path, options = {}) {",
    "      const response = await fetch(path, { headers, ...options });",
    "      if (!response.ok) throw new Error(await response.text());",
    "      return response.json();",
    "    }",
    "    function escapeHtml(value) {",
    "      const element = document.createElement('span');",
    "      element.textContent = String(value);",
    "      return element.innerHTML;",
    "    }",
    "    function renderTicket(ticket) {",
    "      const actions = ticket.allowedTransitions",
    '        .map((status) => \'<button data-id="\' + ticket.id + \'" data-version="\' + ticket.version + \'" data-status="\' + status + \'">\' + status.replaceAll("-", " ") + "</button>")',
    '        .join(" ");',
    '      return \'<article class="ticket"><strong>\' + escapeHtml(ticket.subject) + "</strong><p>" + ticket.presentation.label + " · " + ticket.severityPresentation.label + " · SLA " + ticket.severityPresentation.slaHours + "h</p><span class=\\"meta\\">" + escapeHtml(ticket.memo || "No internal note") + " · version " + ticket.version + "</span><p>" + actions + "</p></article>";',
    "    }",
    "    async function loadTickets() {",
    "      try { ticketList.innerHTML = (await api('/api/tickets')).map(renderTicket).join(''); }",
    "      catch (error) { ticketList.textContent = error.message; }",
    "    }",
    "    ticketList.addEventListener('click', async (event) => {",
    "      const button = event.target.closest('button[data-status]');",
    "      if (!button) return;",
    "      try {",
    "        await api('/api/tickets/' + button.dataset.id + '/status', { method: 'PATCH', body: JSON.stringify({ to: button.dataset.status, expectedVersion: Number(button.dataset.version) }) });",
    "        await loadTickets();",
    "      } catch (error) { alert('Another agent may have moved this ticket: ' + error.message); }",
    "    });",
    "    document.querySelector('#create').addEventListener('submit', async (event) => {",
    "      event.preventDefault();",
    "      const formElement = event.currentTarget;",
    "      const form = new FormData(formElement);",
    "      try {",
    "      await api('/api/tickets', { method: 'POST', body: JSON.stringify(Object.fromEntries(form)) });",
    "      formElement.reset();",
    "      await loadTickets();",
    "      } catch (error) { alert(error.message); }",
    "    });",
    "    void loadTickets();",
    "  </script>",
    "</body>",
    "</html>",
  ].join("\n");
}
